name: sea-lion-app

services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      branch: v2.5
      deploy_on_push: true
      repo: nikrow/Bodega-app
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    source_dir: /
    health_check:
      http_path: /health
      port: 8080
    envs:
      - key: APP_NAME
        scope: RUN_TIME
        value: Laravel
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: APP_KEY
        scope: RUN_TIME
        value: ${APP_KEY}
      - key: APP_DEBUG
        scope: RUN_TIME
        value: "false"
      - key: APP_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: LOG_CHANNEL
        scope: RUN_TIME
        value: stack
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: debug
      - key: DB_CONNECTION
        scope: RUN_TIME
        value: mysql
      - key: DB_HOST
        scope: RUN_TIME
        value: ${DB_HOST}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${DB_PORT}
      - key: DB_DATABASE
        scope: RUN_TIME
        value: ${DB_DATABASE}
      - key: DB_USERNAME
        scope: RUN_TIME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${DB_PASSWORD}
      - key: COMPOSER_ALLOW_SUPERUSER
        scope: BUILD_TIME
        value: "1"

workers:
  - name: worker-bodega-app
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: nikrow/Bodega-app
    run_command: >
      sh -c "php artisan queue:work --tries=3 --timeout=90 --no-interaction & while true; do php artisan schedule:run; sleep 60; done"
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: APP_NAME
        scope: RUN_TIME
        value: Laravel
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: APP_KEY
        scope: RUN_TIME
        value: ${APP_KEY}
      - key: APP_DEBUG
        scope: RUN_TIME
        value: "false"
      - key: APP_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: DB_CONNECTION
        scope: RUN_TIME
        value: mysql
      - key: DB_HOST
        scope: RUN_TIME
        value: ${DB_HOST}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${DB_PORT}
      - key: DB_DATABASE
        scope: RUN_TIME
        value: ${DB_DATABASE}
      - key: DB_USERNAME
        scope: RUN_TIME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${DB_PASSWORD}
jobs:
  - name: post-deploy-job
    dockerfile_path: Dockerfile
    github:
      branch: v2.5
      deploy_on_push: true
      repo: nikrow/Bodega-app
    kind: POST_DEPLOY
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: |
      php artisan cache:clear
      composer dump-autoload
      php artisan migrate --force
      php artisan config:cache
      php artisan event:cache
      php artisan route:cache
      php artisan view:cache
      php artisan optimize
      php artisan filament:optimize
    envs:
      - key: APP_NAME
        scope: RUN_TIME
        value: Laravel
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: APP_KEY
        scope: RUN_TIME
        value: ${APP_KEY}
      - key: APP_DEBUG
        scope: RUN_TIME
        value: "false"
      - key: APP_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: DB_CONNECTION
        scope: RUN_TIME
        value: mysql
      - key: DB_HOST
        scope: RUN_TIME
        value: ${DB_HOST}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${DB_PORT}
      - key: DB_DATABASE
        scope: RUN_TIME
        value: ${DB_DATABASE}
      - key: DB_USERNAME
        scope: RUN_TIME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${DB_PASSWORD}
      - key: COMPOSER_ALLOW_SUPERUSER
        scope: BUILD_TIME
        value: "1"