services:
  frankenphp:
    build:
    command: ["php", "artisan", "octane:frankenphp", "--host=0.0.0.0", "--port=8080", "--workers=4"]
    ports:
      - "8080:8080"
    environment:
      XDEBUG_MODE: 'off'
      IGNITION_LOCAL_SITES_PATH: '/app'
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      SERVER_NAME: campo.gjs.cl
    # volumes:
    restart: unless-stopped
    networks:
      - sail
networks:
  sail:
    driver: bridge